https://github.com/chatopera/cskefu/issues/688 fix mvn cli issue

diff --git a/.github/workflows/pr_checks_package.yml b/.github/workflows/pr_checks_package.yml
--- a/.github/workflows/pr_checks_package.yml
+++ b/.github/workflows/pr_checks_package.yml
@@ -12,7 +12,8 @@ jobs:
           ref: ${{ github.event.pull_request.head.sha }}
       - run: |
           cd $GITHUB_WORKSPACE && pwd
-          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/chatopera/cskefu/issues/688"; exit 1 fi
+          if [ ! -d .git ]; then git init; git config user.email "you@dummy.com"; git config user.name "dummy"; git add --all && git commit -m "empty"; fi
+          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/chatopera/cskefu/issues/688"; exit 1; fi
           java -version && mvn -version
           $GITHUB_WORKSPACE/public/plugins/scripts/install-all.sh
           cd $GITHUB_WORKSPACE/contact-center && ./admin/package.sh
