https://github.com/cskefu/cskefu-docs/issues/6 update docs link in sourcecodes

diff --git a/.github/workflows/pr_checks_package.yml b/.github/workflows/pr_checks_package.yml
--- a/.github/workflows/pr_checks_package.yml
+++ b/.github/workflows/pr_checks_package.yml
@@ -13,7 +13,7 @@ jobs:
       - run: |
           cd $GITHUB_WORKSPACE && pwd
           if [ ! -d .git ]; then git init; git config user.email "you@dummy.com"; git config user.name "dummy"; git add --all && git commit -q -m "Only fix mvn goals for github workflow"; fi
-          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/chatopera/cskefu/issues/688"; exit 1; fi
+          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/cskefu/cskefu/issues/688"; exit 1; fi
           java -version && mvn -version
           $GITHUB_WORKSPACE/public/plugins/scripts/install-all.sh
           cd $GITHUB_WORKSPACE/contact-center && ./admin/package.sh
